$("#GPLocalStorageSave").on("click", function(event) {

      event.preventDefault();
      let GPOpenPennies = $("#WSCOpenPennies").val().trim();
      let GPMidPennies = $("#WSCMidPennies").val().trim();
      let GPClosePennies = $("#WSCClosePennies").val().trim();
      let GPOpenNickels = $("#WSCOpenNickels").val().trim();
      let GPMidNickels = $("#WSCMidNickels").val().trim();
      let GPCloseNickels = $("#WSCCloseNickels").val().trim();
      let GPOpenDimes = $("#WSCOpenDimes").val().trim();
      let GPMidDimes = $("#WSCMidDimes").val().trim();
      let GPCloseDimes = $("#WSCCloseDimes").val().trim();
      let GPOpenQuarters = $("#WSCOpenQuarters").val().trim();
      let GPMidQuarters = $("#WSCMidQuarters").val().trim();
      let GPCloseQuarters = $("#WSCCloseQuarters").val().trim();
      let GPOpenOnes = $("#WSCOpenOnes").val().trim();
      let GPMidOnes = $("#WSCMidOnes").val().trim();
      let GPCloseOnes = $("#WSCCloseOnes").val().trim();
      let GPOpenFives = $("#WSCOpenFives").val().trim();
      let GPMidFives = $("#WSCMidFives").val().trim();
      let GPCloseFives = $("#WSCCloseFives").val().trim();
      let GPOpenTens = $("#WSCOpenTens").val().trim();
      let GPMidTens = $("#WSCMidTens").val().trim();
      let GPCloseTens = $("#WSCCloseTens").val().trim();
      let GPOpenTwenties = $("#WSCOpenTwenties").val().trim();
      let GPMidTwenties = $("#WSCMidTwenties").val().trim();
      let GPCloseTwenties = $("#WSCCloseTwenties").val().trim();
      let GPOpenFithy = $("#WSCOpenFithy").val().trim();
      let GPMidFithy = $("#WSCMidFithy").val().trim();
      let GPCloseFithy = $("#WSCCloseFithy").val().trim();
      let GPOpenHundreds = $("#WSCOpenHundreds").val().trim();
      let GPMidHundreds = $("#WSCMidHundreds").val().trim();
      let GPCloseHundreds = $("#WSCCloseHundreds").val().trim();
      let GPOpenSafeCount = $("#WSCOpenSafeCount").val().trim();
      let GPMidSafeCount = $("#WSCMidSafeCount").val().trim();
      let GPCloseSafeCount = $("#WSCCloseSafeCount").val().trim();
      let GPOpenRegister = $("#WSCOpenRegister").val().trim();
      let GPMidRegister = $("#WSCMidRegister").val().trim();
      let GPCloseRegister = $("#WSCCloseRegister").val().trim();
      let GPOpenTotalSafe = $("#WSCOpenTotalSafe").val().trim();
      let GPMidTotalSafe = $("#WSCMidTotalSafe").val().trim();
      let GPCloseTotalSafe = $("#WSCCloseTotalSafe").val().trim();
      let GPOpenMgrInitials = $("#WSCOpenMgrInitials").val().trim();
      let GPMidMgrInitials = $("#WSCMidMgrInitials").val().trim();
      let GPCloseMgrInitials = $("#WSCCloseMgrInitials").val().trim();
      let GPPosIdealDeposit1 = $("#RDLPosIdealDeposit1").val().trim();
      let GPPosIdealDeposit2 = $("#RDLPosIdealDeposit2").val().trim();
      let GPPosIdealDeposit3 = $("#RDLPosIdealDeposit3").val().trim();
      let GPPosIdealDepositTotal = $("#RDLPosIdealDepositTotal").val().trim();
      let GPManagerBankDeposit1 = $("#RDLManagerBankDeposit1").val().trim();
      let GPManagerBankDeposit2 = $("#RDLManagerBankDeposit2").val().trim();
      let GPManagerBankDeposit3 = $("#RDLManagerBankDeposit3").val().trim();
      let GPManagerBankDepositTotal = $("#RDLManagerBankDepositTotal").val().trim();
      let GPVariance1 = $("#RDLVariance1").val().trim();
      let GPVariance2 = $("#RDLVariance2").val().trim();
      let GPVariance3 = $("#RDLVariance3").val().trim();
      let GPVarianceTotal = $("#RDLVarianceTotal").val().trim();
      let GPMGRsign1 = $("#RDLMGRsign1").val().trim();
      let GPMGRsign2 = $("#RDLMGRsign2").val().trim();
      let GPMGRsign3 = $("#RDLMGRsign3").val().trim();
      let GPMGRsignTotal = $("#RDLMGRsignTotal").val().trim();
      let GPTook1 = $("#RDLMGRtookDeposits1").val().trim();
      let GPTook2 = $("#RDLMGRtookDeposits2").val().trim();
      let GPTook3 = $("#RDLMGRtookDeposits3").val().trim();
      let GPTookTotal = $("#RDLMGRtookDepositsTotal").val().trim();
      
      localStorage.setItem("LDBWSCOpenPennies",  GPOpenPennies);
      localStorage.setItem("LDBWSCMidPennies",  GPMidPennies);
      localStorage.setItem("LDBWSCClosePennies",  GPClosePennies);
      localStorage.setItem("LDBWSCOpenNickels",  GPOpenNickels);
      localStorage.setItem("LDBWSCMidNickels",  GPMidNickels);
      localStorage.setItem("LDBWSCCloseNickels",  GPCloseNickels);
      localStorage.setItem("LDBWSCOpenDimes",  GPOpenDimes);
      localStorage.setItem("LDBWSCMidDimes",  GPMidDimes);
      localStorage.setItem("LDBWSCCloseDimes",  GPCloseDimes);
      localStorage.setItem("LDBWSCOpenQuarters",  GPOpenQuarters);
      localStorage.setItem("LDBWSCMidQuarters",  GPMidQuarters);
      localStorage.setItem("LDBWSCCloseQuarters",  GPCloseQuarters);
      localStorage.setItem("LDBWSCOpenOnes",  GPOpenOnes);
      localStorage.setItem("LDBWSCMidOnes",  GPMidOnes);
      localStorage.setItem("LDBWSCCloseOnes",  GPCloseOnes);
      localStorage.setItem("LDBWSCOpenFives",  GPOpenFives);
      localStorage.setItem("LDBWSCMidFives",  GPMidFives);
      localStorage.setItem("LDBWSCCloseFives",  GPCloseFives);
      localStorage.setItem("LDBWSCOpenTens",  GPOpenTens);
      localStorage.setItem("LDBWSCMidTens",  GPMidTens);
      localStorage.setItem("LDBWSCCloseTens",  GPCloseTens);
      localStorage.setItem("LDBWSCOpenTens",  GPOpenTens);
      localStorage.setItem("LDBWSCMidTens",  GPMidTens);
      localStorage.setItem("LDBWSCCloseTens",  GPCloseTens);
      localStorage.setItem("LDBWSCOpenTwenties",  GPOpenTwenties);
      localStorage.setItem("LDBWSCMidTwenties",  GPMidTwenties);
      localStorage.setItem("LDBWSCCloseTwenties",  GPCloseTwenties);
      localStorage.setItem("LDBWSCOpenFithy",  GPOpenFithy);
      localStorage.setItem("LDBWSCMidFithy",  GPMidFithy);
      localStorage.setItem("LDBWSCCloseFithy",  GPCloseFithy);
      localStorage.setItem("LDBWSCOpenHundreds",  GPOpenHundreds);
      localStorage.setItem("LDBWSCMidHundreds",  GPMidHundreds);
      localStorage.setItem("LDBWSCCloseHundreds",  GPCloseHundreds);
      localStorage.setItem("LDBWSCOpenSafeCount",  GPOpenSafeCount);
      localStorage.setItem("LDBWSCMidSafeCount",  GPMidSafeCount);
      localStorage.setItem("LDBWSCCloseSafeCount",  GPCloseSafeCount);
      localStorage.setItem("LDBWSCOpenRegister",  GPOpenRegister);
      localStorage.setItem("LDBWSCMidRegister",  GPMidRegister);
      localStorage.setItem("LDBWSCCloseRegister",  GPCloseRegister);
      localStorage.setItem("LDBWSCOpenTotalSafe",  GPOpenTotalSafe);
      localStorage.setItem("LDBWSCMidTotalSafe",  GPMidTotalSafe);
      localStorage.setItem("LDBWSCCloseTotalSafe",  GPCloseTotalSafe);
      localStorage.setItem("LDBWSCOpenMgrInitials",  GPOpenMgrInitials);
      localStorage.setItem("LDBWSCMidMgrInitials",  GPMidMgrInitials);
      localStorage.setItem("LDBWSCCloseMgrInitials",  GPCloseMgrInitials);
      localStorage.setItem("LDBRDLPosIdealDeposit1",  GPPosIdealDeposit1);
      localStorage.setItem("LDBRDLPosIdealDeposit2",  GPPosIdealDeposit2);
      localStorage.setItem("LDBRDLPosIdealDeposit3",  GPPosIdealDeposit3);
      localStorage.setItem("LDBRDLPosIdealDepositTotal",  GPPosIdealDepositTotal);
      localStorage.setItem("LDBRDLManagerBankDeposit1",  GPManagerBankDeposit1);
      localStorage.setItem("LDBRDLManagerBankDeposit2",  GPManagerBankDeposit2);
      localStorage.setItem("LDBRDLManagerBankDeposit3",  GPManagerBankDeposit3);
      localStorage.setItem("LDBRDLManagerBankDepositTotal",  GPManagerBankDepositTotal);
      localStorage.setItem("LDBRDLVariance1",  GPVariance1);
      localStorage.setItem("LDBRDLVariance2",  GPVariance2);
      localStorage.setItem("LDBRDLVariance3",  GPVariance3);
      localStorage.setItem("LDBRDLVarianceTotal",  GPVarianceTotal);
      localStorage.setItem("LDBRDLMGRsign1",  GPMGRsign1);
      localStorage.setItem("LDBRDLMGRsign2",  GPMGRsign2);
      localStorage.setItem("LDBRDLMGRsign3",  GPMGRsign3);
      localStorage.setItem("LDBRDLMGRsignTotal",  GPMGRsignTotal);
      localStorage.setItem("LDBRDLMGRtookDeposits1",  GPTook1);
      localStorage.setItem("LDBRDLMGRtookDeposits2",  GPTook2);
      localStorage.setItem("LDBRDLMGRtookDeposits3",  GPTook3);
      localStorage.setItem("LDBRDLMGRtookDepositsTotal",  GPTookTotal);
    });

$("#GPLocalStorageClear").on("click", function(event) {

      event.preventDefault();
      localStorage.setItem("LDBWSCOpenPennies",  "");
      localStorage.setItem("LDBWSCMidPennies", "");
      localStorage.setItem("LDBWSCClosePennies", "");
      localStorage.setItem("LDBWSCOpenNickels", "");
      localStorage.setItem("LDBWSCMidNickels", "");
      localStorage.setItem("LDBWSCCloseNickels", "");
      localStorage.setItem("LDBWSCOpenDimes", "");
      localStorage.setItem("LDBWSCMidDimes", "");
      localStorage.setItem("LDBWSCCloseDimes", "");
      localStorage.setItem("LDBWSCOpenQuarters", "");
      localStorage.setItem("LDBWSCMidQuarters", "");
      localStorage.setItem("LDBWSCCloseQuarters", "");
      localStorage.setItem("LDBWSCOpenOnes", "");
      localStorage.setItem("LDBWSCMidOnes", "");
      localStorage.setItem("LDBWSCCloseOnes", "");
      localStorage.setItem("LDBWSCOpenFives", "");
      localStorage.setItem("LDBWSCMidFives", "");
      localStorage.setItem("LDBWSCCloseFives", "");
      localStorage.setItem("LDBWSCOpenTens", "");
      localStorage.setItem("LDBWSCMidTens", "");
      localStorage.setItem("LDBWSCCloseTens", "");
      localStorage.setItem("LDBWSCOpenTens", "");
      localStorage.setItem("LDBWSCMidTens", "");
      localStorage.setItem("LDBWSCCloseTens", "");
      localStorage.setItem("LDBWSCOpenTwenties", "");
      localStorage.setItem("LDBWSCMidTwenties", "");
      localStorage.setItem("LDBWSCCloseTwenties", "");
      localStorage.setItem("LDBWSCOpenFithy", "");
      localStorage.setItem("LDBWSCMidFithy", "");
      localStorage.setItem("LDBWSCCloseFithy", "");
      localStorage.setItem("LDBWSCOpenHundreds", "");
      localStorage.setItem("LDBWSCMidHundreds", "");
      localStorage.setItem("LDBWSCCloseHundreds", "");
      localStorage.setItem("LDBWSCOpenSafeCount", "");
      localStorage.setItem("LDBWSCMidSafeCount", "");
      localStorage.setItem("LDBWSCCloseSafeCount", "");
      localStorage.setItem("LDBWSCOpenRegister", "");
      localStorage.setItem("LDBWSCMidRegister", "");
      localStorage.setItem("LDBWSCCloseRegister", "");
      localStorage.setItem("LDBWSCOpenTotalSafe", "");
      localStorage.setItem("LDBWSCMidTotalSafe", "");
      localStorage.setItem("LDBWSCCloseTotalSafe", "");
      localStorage.setItem("LDBWSCOpenMgrInitials", "");
      localStorage.setItem("LDBWSCMidMgrInitials", "");
      localStorage.setItem("LDBWSCCloseMgrInitials", "");
      localStorage.setItem("LDBRDLPosIdealDeposit1", "");
      localStorage.setItem("LDBRDLPosIdealDeposit2", "");
      localStorage.setItem("LDBRDLPosIdealDeposit3", "");
      localStorage.setItem("LDBRDLPosIdealDepositTotal", "");
      localStorage.setItem("LDBRDLManagerBankDeposit1", "");
      localStorage.setItem("LDBRDLManagerBankDeposit2", "");
      localStorage.setItem("LDBRDLManagerBankDeposit3", "");
      localStorage.setItem("LDBRDLManagerBankDepositTotal", "");
      localStorage.setItem("LDBRDLVariance1", "");
      localStorage.setItem("LDBRDLVariance2", "");
      localStorage.setItem("LDBRDLVariance3", "");
      localStorage.setItem("LDBRDLVarianceTotal", "");
      localStorage.setItem("LDBRDLMGRsign1", "");
      localStorage.setItem("LDBRDLMGRsign2", "");
      localStorage.setItem("LDBRDLMGRsign3", "");
      localStorage.setItem("LDBRDLMGRsignTotal", "");
      localStorage.setItem("LDBRDLMGRtookDeposits1", "");
      localStorage.setItem("LDBRDLMGRtookDeposits2", "");
      localStorage.setItem("LDBRDLMGRtookDeposits3", "");
      localStorage.setItem("LDBRDLMGRtookDepositsTotal", "");
    
      $("#WSCOpenPennies").val(localStorage.getItem("LDBWSCOpenPennies"));
      $("#WSCMidPennies").val(localStorage.getItem("LDBWSCMidPennies"));
      $("#WSCClosePennies").val(localStorage.getItem("LDBWSCClosePennies"));
      $("#WSCOpenNickels").val(localStorage.getItem("LDBWSCOpenNickels"));
      $("#WSCMidNickels").val(localStorage.getItem("LDBWSCMidNickels"));
      $("#WSCCloseNickels").val(localStorage.getItem("LDBWSCCloseNickels"));
      $("#WSCOpenDimes").val(localStorage.getItem("LDBWSCOpenDimes"));
      $("#WSCMidDimes").val(localStorage.getItem("LDBWSCOpenPennies"));
      $("#WSCCloseDimes").val(localStorage.getItem("LDBWSCOpenPennies"));
      $("#WSCOpenQuarters").val(localStorage.getItem("LDBWSCOpenQuarters"));
      $("#WSCMidQuarters").val(localStorage.getItem("LDBWSCMidQuarters"));
      $("#WSCCloseQuarters").val(localStorage.getItem("LDBWSCCloseQuarters"));
      $("#WSCOpenOnes").val(localStorage.getItem("LDBWSCOpenOnes"));
      $("#WSCMidOnes").val(localStorage.getItem("LDBWSCMidOnes"));
      $("#WSCCloseOnes").val(localStorage.getItem("LDBWSCCloseOnes"));
      $("#WSCOpenFives").val(localStorage.getItem("LDBWSCOpenFives"));
      $("#WSCMidFives").val(localStorage.getItem("LDBWSCMidFives"));
      $("#WSCCloseFives").val(localStorage.getItem("LDBWSCCloseFives"));
      $("#WSCOpenTens").val(localStorage.getItem("LDBWSCOpenTens"));
      $("#WSCMidTens").val(localStorage.getItem("LDBWSCMidTens"));
      $("#WSCCloseTens").val(localStorage.getItem("LDBWSCCloseTens"));
      $("#WSCOpenTwenties").val(localStorage.getItem("LDBWSCOpenTwenties"));
      $("#WSCMidTwenties").val(localStorage.getItem("LDBWSCMidTwenties"));
      $("#WSCCloseTwenties").val(localStorage.getItem("LDBWSCCloseTwenties"));
      $("#WSCOpenFifthy").val(localStorage.getItem("LDBWSCOpenFifthy"));
      $("#WSCMidFifthy").val(localStorage.getItem("LDBWSCMidFifthy"));
      $("#WSCCloseFifthy").val(localStorage.getItem("LDBWSCCloseFifthy"));
      $("#WSCOpenHundreds").val(localStorage.getItem("LDBWSCOpenHundreds"));
      $("#WSCMidHundreds").val(localStorage.getItem("LDBWSCMidHundreds"));
      $("#WSCCloseHundreds").val(localStorage.getItem("LDBWSCCloseHundreds"));
      $("#WSCOpenSafeCount").val(localStorage.getItem("LDBWSCOpenSafeCount"));
      $("#WSCMidSafeCount").val(localStorage.getItem("LDBWSCMidSafeCount"));
      $("#WSCCloseSafeCount").val(localStorage.getItem("LDBWSCCloseSafeCount"));
      $("#WSCOpenRegister").val(localStorage.getItem("LDBWSCOpenRegister"));
      $("#WSCMidRegister").val(localStorage.getItem("LDBWSCMidRegister"));
      $("#WSCCloseRegister").val(localStorage.getItem("LDBWSCCloseRegister"));
      $("#WSCOpenTotalSafe").val(localStorage.getItem("LDBWSCOpenTotalSafe"));
      $("#WSCMidTotalSafe").val(localStorage.getItem("LDBWSCMidTotalSafe"));
      $("#WSCCloseTotalSafe").val(localStorage.getItem("LDBWSCCloseTotalSafe"));
      $("#WSCOpenMgrInitials").val(localStorage.getItem("LDBWSCOpenMgrInitials"));
      $("#WSCMidMgrInitials").val(localStorage.getItem("LDBWSCMidMgrInitials"));
      $("#WSCCloseMgrInitials").val(localStorage.getItem("LDBWSCCloseMgrInitials"));
      $("#RDLPosIdealDeposit1").val(localStorage.getItem("LDBRDLPosIdealDeposit1"));
      $("#RDLPosIdealDeposit2").val(localStorage.getItem("LDBRDLPosIdealDeposit2"));
      $("#RDLPosIdealDeposit3").val(localStorage.getItem("LDBLDRDLPosIdealDeposit3"));
      $("#RDLPosIdealDepositTotal").val(localStorage.getItem("LDBRDLPosIdealDepositTotal"));
      $("#RDLManagerBankDeposit1").val(localStorage.getItem("LDBRDLManagerBankDeposit1"));
      $("#RDLManagerBankDeposit2").val(localStorage.getItem("LDBRDLManagerBankDeposit2"));
      $("#RDLManagerBankDeposit3").val(localStorage.getItem("LDBRDLManagerBankDeposit3"));
      $("#RDLManagerBankDepositTotal").val(localStorage.getItem("LDBRDLManagerBankDepositTotal"));
      $("#RDLVariance1").val(localStorage.getItem("LDBRDLVariance1"));
      $("#RDLVariance2").val(localStorage.getItem("LDBRDLVariance2"));
      $("#RDLVariance3").val(localStorage.getItem("LDBRDLVariance3"));
      $("#RDLVarianceTotal").val(localStorage.getItem("LDBRDLVarianceTotal"));
      $("#RDLMGRsign1").val(localStorage.getItem("LDBRDLMGRsign1"));
      $("#RDLMGRsign2").val(localStorage.getItem("LDBRDLMGRsign2"));
      $("#RDLMGRsign3").val(localStorage.getItem("LDBRDLMGRsign3"));
      $("#RDLMGRsignTotal").val(localStorage.getItem("LDBRDLMGRsignTotal"));
      $("#RDLMGRtookDeposits1").val(localStorage.getItem("LDBRDLMGRtookDeposits1"));
      $("#RDLMGRtookDeposits2").val(localStorage.getItem("LDBRDLMGRtookDeposits2"));
      $("#RDLMGRtookDeposits3").val(localStorage.getItem("LDBRDLMGRtookDeposits3"));
      $("#RDLMGRtookDepositsTotal").val(localStorage.getItem("LDBRDLMGRtookDepositsTotal"));

    });


      $("#WSCOpenPennies").val(localStorage.getItem("LDBWSCOpenPennies"));
      $("#WSCMidPennies").val(localStorage.getItem("LDBWSCMidPennies"));
      $("#WSCClosePennies").val(localStorage.getItem("LDBWSCClosePennies"));
      $("#WSCOpenNickels").val(localStorage.getItem("LDBWSCOpenNickels"));
      $("#WSCMidNickels").val(localStorage.getItem("LDBWSCMidNickels"));
      $("#WSCCloseNickels").val(localStorage.getItem("LDBWSCCloseNickels"));
      $("#WSCOpenDimes").val(localStorage.getItem("LDBWSCOpenDimes"));
      $("#WSCMidDimes").val(localStorage.getItem("LDBWSCOpenPennies"));
      $("#WSCCloseDimes").val(localStorage.getItem("LDBWSCOpenPennies"));
      $("#WSCOpenQuarters").val(localStorage.getItem("LDBWSCOpenQuarters"));
      $("#WSCMidQuarters").val(localStorage.getItem("LDBWSCMidQuarters"));
      $("#WSCCloseQuarters").val(localStorage.getItem("LDBWSCCloseQuarters"));
      $("#WSCOpenOnes").val(localStorage.getItem("LDBWSCOpenOnes"));
      $("#WSCMidOnes").val(localStorage.getItem("LDBWSCMidOnes"));
      $("#WSCCloseOnes").val(localStorage.getItem("LDBWSCCloseOnes"));
      $("#WSCOpenFives").val(localStorage.getItem("LDBWSCOpenFives"));
      $("#WSCMidFives").val(localStorage.getItem("LDBWSCMidFives"));
      $("#WSCCloseFives").val(localStorage.getItem("LDBWSCCloseFives"));
      $("#WSCOpenTens").val(localStorage.getItem("LDBWSCOpenTens"));
      $("#WSCMidTens").val(localStorage.getItem("LDBWSCMidTens"));
      $("#WSCCloseTens").val(localStorage.getItem("LDBWSCCloseTens"));
      $("#WSCOpenTwenties").val(localStorage.getItem("LDBWSCOpenTwenties"));
      $("#WSCMidTwenties").val(localStorage.getItem("LDBWSCMidTwenties"));
      $("#WSCCloseTwenties").val(localStorage.getItem("LDBWSCCloseTwenties"));
      $("#WSCOpenFifthy").val(localStorage.getItem("LDBWSCOpenFifthy"));
      $("#WSCMidFifthy").val(localStorage.getItem("LDBWSCMidFifthy"));
      $("#WSCCloseFifthy").val(localStorage.getItem("LDBWSCCloseFifthy"));
      $("#WSCOpenHundreds").val(localStorage.getItem("LDBWSCOpenHundreds"));
      $("#WSCMidHundreds").val(localStorage.getItem("LDBWSCMidHundreds"));
      $("#WSCCloseHundreds").val(localStorage.getItem("LDBWSCCloseHundreds"));
      $("#WSCOpenSafeCount").val(localStorage.getItem("LDBWSCOpenSafeCount"));
      $("#WSCMidSafeCount").val(localStorage.getItem("LDBWSCMidSafeCount"));
      $("#WSCCloseSafeCount").val(localStorage.getItem("LDBWSCCloseSafeCount"));
      $("#WSCOpenRegister").val(localStorage.getItem("LDBWSCOpenRegister"));
      $("#WSCMidRegister").val(localStorage.getItem("LDBWSCMidRegister"));
      $("#WSCCloseRegister").val(localStorage.getItem("LDBWSCCloseRegister"));
      $("#WSCOpenTotalSafe").val(localStorage.getItem("LDBWSCOpenTotalSafe"));
      $("#WSCMidTotalSafe").val(localStorage.getItem("LDBWSCMidTotalSafe"));
      $("#WSCCloseTotalSafe").val(localStorage.getItem("LDBWSCCloseTotalSafe"));
      $("#WSCOpenMgrInitials").val(localStorage.getItem("LDBWSCOpenMgrInitials"));
      $("#WSCMidMgrInitials").val(localStorage.getItem("LDBWSCMidMgrInitials"));
      $("#WSCCloseMgrInitials").val(localStorage.getItem("LDBWSCCloseMgrInitials"));
      $("#RDLPosIdealDeposit1").val(localStorage.getItem("LDBRDLPosIdealDeposit1"));
      $("#RDLPosIdealDeposit2").val(localStorage.getItem("LDBRDLPosIdealDeposit2"));
      $("#RDLPosIdealDeposit3").val(localStorage.getItem("LDBLDRDLPosIdealDeposit3"));
      $("#RDLPosIdealDepositTotal").val(localStorage.getItem("LDBRDLPosIdealDepositTotal"));
      $("#RDLManagerBankDeposit1").val(localStorage.getItem("LDBRDLManagerBankDeposit1"));
      $("#RDLManagerBankDeposit2").val(localStorage.getItem("LDBRDLManagerBankDeposit2"));
      $("#RDLManagerBankDeposit3").val(localStorage.getItem("LDBRDLManagerBankDeposit3"));
      $("#RDLManagerBankDepositTotal").val(localStorage.getItem("LDBRDLManagerBankDepositTotal"));
      $("#RDLVariance1").val(localStorage.getItem("LDBRDLVariance1"));
      $("#RDLVariance2").val(localStorage.getItem("LDBRDLVariance2"));
      $("#RDLVariance3").val(localStorage.getItem("LDBRDLVariance3"));
      $("#RDLVarianceTotal").val(localStorage.getItem("LDBRDLVarianceTotal"));
      $("#RDLMGRsign1").val(localStorage.getItem("LDBRDLMGRsign1"));
      $("#RDLMGRsign2").val(localStorage.getItem("LDBRDLMGRsign2"));
      $("#RDLMGRsign3").val(localStorage.getItem("LDBRDLMGRsign3"));
      $("#RDLMGRsignTotal").val(localStorage.getItem("LDBRDLMGRsignTotal"));
      $("#RDLMGRtookDeposits1").val(localStorage.getItem("LDBRDLMGRtookDeposits1"));
      $("#RDLMGRtookDeposits2").val(localStorage.getItem("LDBRDLMGRtookDeposits2"));
      $("#RDLMGRtookDeposits3").val(localStorage.getItem("LDBRDLMGRtookDeposits3"));
      $("#RDLMGRtookDepositsTotal").val(localStorage.getItem("LDBRDLMGRtookDepositsTotal"));

      

    