


let today = new Date();
let dd = today.getDate();
let mm = today.getMonth()+1;
let yyyy = today.getFullYear();
let lastDate;

if(dd<10) {
    dd = '0'+dd
} 
if(mm<10) {
    mm = '0'+mm
} 
today = mm + '/' + dd + '/' + yyyy;
$("#DSCDate").text(today);
$("#RDLDate").text(today);

/*if (today !== lastDate) {
  GPclearStore();
  lastDate=today};
*/
$("#GPLocalStorageSave").on("click", GPstore);
$("#GPLocalStorageClear").on("click", GPclearStore);



      $("#DSCOpenPennies").val(localStorage.getItem("LDBDSCOpenPennies"));
      $("#DSCMidPennies").val(localStorage.getItem("LDBDSCMidPennies"));
      $("#DSCClosePennies").val(localStorage.getItem("LDBDSCClosePennies"));
      $("#DSCOpenNickels").val(localStorage.getItem("LDBDSCOpenNickels"));
      $("#DSCMidNickels").val(localStorage.getItem("LDBDSCMidNickels"));
      $("#DSCCloseNickels").val(localStorage.getItem("LDBDSCCloseNickels"));
      $("#DSCOpenDimes").val(localStorage.getItem("LDBDSCOpenDimes"));
      $("#DSCMidDimes").val(localStorage.getItem("LDBDSCOpenDimes"));
      $("#DSCCloseDimes").val(localStorage.getItem("LDBDSCOpenDimes"));
      $("#DSCOpenQuarters").val(localStorage.getItem("LDBDSCOpenQuarters"));
      $("#DSCMidQuarters").val(localStorage.getItem("LDBDSCMidQuarters"));
      $("#DSCCloseQuarters").val(localStorage.getItem("LDBDSCCloseQuarters"));
      $("#DSCOpenOnes").val(localStorage.getItem("LDBDSCOpenOnes"));
      $("#DSCMidOnes").val(localStorage.getItem("LDBDSCMidOnes"));
      $("#DSCCloseOnes").val(localStorage.getItem("LDBDSCCloseOnes"));
      $("#DSCOpenFives").val(localStorage.getItem("LDBDSCOpenFives"));
      $("#DSCMidFives").val(localStorage.getItem("LDBDSCMidFives"));
      $("#DSCCloseFives").val(localStorage.getItem("LDBDSCCloseFives"));
      $("#DSCOpenTens").val(localStorage.getItem("LDBDSCOpenTens"));
      $("#DSCMidTens").val(localStorage.getItem("LDBDSCMidTens"));
      $("#DSCCloseTens").val(localStorage.getItem("LDBDSCCloseTens"));
      $("#DSCOpenTwenties").val(localStorage.getItem("LDBDSCOpenTwenties"));
      $("#DSCMidTwenties").val(localStorage.getItem("LDBDSCMidTwenties"));
      $("#DSCCloseTwenties").val(localStorage.getItem("LDBDSCCloseTwenties"));
      $("#DSCOpenFifthy").val(localStorage.getItem("LDBDSCOpenFifthy"));
      $("#DSCMidFifthy").val(localStorage.getItem("LDBDSCMidFifthy"));
      $("#DSCCloseFifthy").val(localStorage.getItem("LDBDSCCloseFifthy"));
      $("#DSCOpenHundreds").val(localStorage.getItem("LDBDSCOpenHundreds"));
      $("#DSCMidHundreds").val(localStorage.getItem("LDBDSCMidHundreds"));
      $("#DSCCloseHundreds").val(localStorage.getItem("LDBDSCCloseHundreds"));
      $("#DSCOpenSafeCount").val(localStorage.getItem("LDBDSCOpenSafeCount"));
      $("#DSCMidSafeCount").val(localStorage.getItem("LDBDSCMidSafeCount"));
      $("#DSCCloseSafeCount").val(localStorage.getItem("LDBDSCCloseSafeCount"));
      $("#DSCOpenRegister").val(localStorage.getItem("LDBDSCOpenRegister"));
      $("#DSCMidRegister").val(localStorage.getItem("LDBDSCMidRegister"));
      $("#DSCCloseRegister").val(localStorage.getItem("LDBDSCCloseRegister"));
      $("#DSCOpenTotalSafe").val(localStorage.getItem("LDBDSCOpenTotalSafe"));
      $("#DSCMidTotalSafe").val(localStorage.getItem("LDBDSCMidTotalSafe"));
      $("#DSCCloseTotalSafe").val(localStorage.getItem("LDBDSCCloseTotalSafe"));
      $("#DSCOpenMgrInitials").val(localStorage.getItem("LDBDSCOpenMgrInitials"));
      $("#DSCMidMgrInitials").val(localStorage.getItem("LDBDSCMidMgrInitials"));
      $("#DSCCloseMgrInitials").val(localStorage.getItem("LDBDSCCloseMgrInitials"));
      $("#RDLPosIdealDeposit1").val(localStorage.getItem("LDBRDLPosIdealDeposit1"));
      $("#RDLPosIdealDeposit2").val(localStorage.getItem("LDBRDLPosIdealDeposit2"));
      $("#RDLPosIdealDeposit3").val(localStorage.getItem("LDBLDRDLPosIdealDeposit3"));
      $("#RDLPosIdealDepositTotal").val(localStorage.getItem("LDBRDLPosIdealDepositTotal"));
      $("#RDLManagerBankDeposit1").val(localStorage.getItem("LDBRDLManagerBankDeposit1"));
      $("#RDLManagerBankDeposit2").val(localStorage.getItem("LDBRDLManagerBankDeposit2"));
      $("#RDLManagerBankDeposit3").val(localStorage.getItem("LDBRDLManagerBankDeposit3"));
      $("#RDLManagerBankDepositTotal").val(localStorage.getItem("LDBRDLManagerBankDepositTotal"));
      $("#RDLVariance1").val(localStorage.getItem("LDBRDLVariance1"));
      $("#RDLVariance2").val(localStorage.getItem("LDBRDLVariance2"));
      $("#RDLVariance3").val(localStorage.getItem("LDBRDLVariance3"));
      $("#RDLVarianceTotal").val(localStorage.getItem("LDBRDLVarianceTotal"));
      $("#RDLMGRsign1").val(localStorage.getItem("LDBRDLMGRsign1"));
      $("#RDLMGRsign2").val(localStorage.getItem("LDBRDLMGRsign2"));
      $("#RDLMGRsign3").val(localStorage.getItem("LDBRDLMGRsign3"));
      $("#RDLMGRsignTotal").val(localStorage.getItem("LDBRDLMGRsignTotal"));
      $("#RDLMGRtookDeposits1").val(localStorage.getItem("LDBRDLMGRtookDeposits1"));
      $("#RDLMGRtookDeposits2").val(localStorage.getItem("LDBRDLMGRtookDeposits2"));
      $("#RDLMGRtookDeposits3").val(localStorage.getItem("LDBRDLMGRtookDeposits3"));
      $("#RDLMGRtookDepositsTotal").val(localStorage.getItem("LDBRDLMGRtookDepositsTotal"));

function GPstore() {
      let GPOpenPennies = $("#DSCOpenPennies").val().trim();
      let GPMidPennies = $("#DSCMidPennies").val().trim();
      let GPClosePennies = $("#DSCClosePennies").val().trim();
      let GPOpenNickels = $("#DSCOpenNickels").val().trim();
      let GPMidNickels = $("#DSCMidNickels").val().trim();
      let GPCloseNickels = $("#DSCCloseNickels").val().trim();
      let GPOpenDimes = $("#DSCOpenDimes").val().trim();
      let GPMidDimes = $("#DSCMidDimes").val().trim();
      let GPCloseDimes = $("#DSCCloseDimes").val().trim();
      let GPOpenQuarters = $("#DSCOpenQuarters").val().trim();
      let GPMidQuarters = $("#DSCMidQuarters").val().trim();
      let GPCloseQuarters = $("#DSCCloseQuarters").val().trim();
      let GPOpenOnes = $("#DSCOpenOnes").val().trim();
      let GPMidOnes = $("#DSCMidOnes").val().trim();
      let GPCloseOnes = $("#DSCCloseOnes").val().trim();
      let GPOpenFives = $("#DSCOpenFives").val().trim();
      let GPMidFives = $("#DSCMidFives").val().trim();
      let GPCloseFives = $("#DSCCloseFives").val().trim();
      let GPOpenTens = $("#DSCOpenTens").val().trim();
      let GPMidTens = $("#DSCMidTens").val().trim();
      let GPCloseTens = $("#DSCCloseTens").val().trim();
      let GPOpenTwenties = $("#DSCOpenTwenties").val().trim();
      let GPMidTwenties = $("#DSCMidTwenties").val().trim();
      let GPCloseTwenties = $("#DSCCloseTwenties").val().trim();
      let GPOpenFithy = $("#DSCOpenFithy").val().trim();
      let GPMidFithy = $("#DSCMidFithy").val().trim();
      let GPCloseFithy = $("#DSCCloseFithy").val().trim();
      let GPOpenHundreds = $("#DSCOpenHundreds").val().trim();
      let GPMidHundreds = $("#DSCMidHundreds").val().trim();
      let GPCloseHundreds = $("#DSCCloseHundreds").val().trim();
      let GPOpenSafeCount = $("#DSCOpenSafeCount").val().trim();
      let GPMidSafeCount = $("#DSCMidSafeCount").val().trim();
      let GPCloseSafeCount = $("#DSCCloseSafeCount").val().trim();
      let GPOpenRegister = $("#DSCOpenRegister").val().trim();
      let GPMidRegister = $("#DSCMidRegister").val().trim();
      let GPCloseRegister = $("#DSCCloseRegister").val().trim();
      let GPOpenTotalSafe = $("#DSCOpenTotalSafe").val().trim();
      let GPMidTotalSafe = $("#DSCMidTotalSafe").val().trim();
      let GPCloseTotalSafe = $("#DSCCloseTotalSafe").val().trim();
      let GPOpenMgrInitials = $("#DSCOpenMgrInitials").val().trim();
      let GPMidMgrInitials = $("#DSCMidMgrInitials").val().trim();
      let GPCloseMgrInitials = $("#DSCCloseMgrInitials").val().trim();
      let GPPosIdealDeposit1 = $("#RDLPosIdealDeposit1").val().trim();
      let GPPosIdealDeposit2 = $("#RDLPosIdealDeposit2").val().trim();
      let GPPosIdealDeposit3 = $("#RDLPosIdealDeposit3").val().trim();
      let GPPosIdealDepositTotal = $("#RDLPosIdealDepositTotal").val().trim();
      let GPManagerBankDeposit1 = $("#RDLManagerBankDeposit1").val().trim();
      let GPManagerBankDeposit2 = $("#RDLManagerBankDeposit2").val().trim();
      let GPManagerBankDeposit3 = $("#RDLManagerBankDeposit3").val().trim();
      let GPManagerBankDepositTotal = $("#RDLManagerBankDepositTotal").val().trim();
      let GPVariance1 = $("#RDLVariance1").val().trim();
      let GPVariance2 = $("#RDLVariance2").val().trim();
      let GPVariance3 = $("#RDLVariance3").val().trim();
      let GPVarianceTotal = $("#RDLVarianceTotal").val().trim();
      let GPMGRsign1 = $("#RDLMGRsign1").val().trim();
      let GPMGRsign2 = $("#RDLMGRsign2").val().trim();
      let GPMGRsign3 = $("#RDLMGRsign3").val().trim();
      let GPMGRsignTotal = $("#RDLMGRsignTotal").val().trim();
      let GPTook1 = $("#RDLMGRtookDeposits1").val().trim();
      let GPTook2 = $("#RDLMGRtookDeposits2").val().trim();
      let GPTook3 = $("#RDLMGRtookDeposits3").val().trim();
      let GPTookTotal = $("#RDLMGRtookDepositsTotal").val().trim();
      
      localStorage.setItem("LDBDSCOpenPennies",  GPOpenPennies);
      localStorage.setItem("LDBDSCMidPennies",  GPMidPennies);
      localStorage.setItem("LDBDSCClosePennies",  GPClosePennies);
      localStorage.setItem("LDBDSCOpenNickels",  GPOpenNickels);
      localStorage.setItem("LDBDSCMidNickels",  GPMidNickels);
      localStorage.setItem("LDBDSCCloseNickels",  GPCloseNickels);
      localStorage.setItem("LDBDSCOpenDimes",  GPOpenDimes);
      localStorage.setItem("LDBDSCMidDimes",  GPMidDimes);
      localStorage.setItem("LDBDSCCloseDimes",  GPCloseDimes);
      localStorage.setItem("LDBDSCOpenQuarters",  GPOpenQuarters);
      localStorage.setItem("LDBDSCMidQuarters",  GPMidQuarters);
      localStorage.setItem("LDBDSCCloseQuarters",  GPCloseQuarters);
      localStorage.setItem("LDBDSCOpenOnes",  GPOpenOnes);
      localStorage.setItem("LDBDSCMidOnes",  GPMidOnes);
      localStorage.setItem("LDBDSCCloseOnes",  GPCloseOnes);
      localStorage.setItem("LDBDSCOpenFives",  GPOpenFives);
      localStorage.setItem("LDBDSCMidFives",  GPMidFives);
      localStorage.setItem("LDBDSCCloseFives",  GPCloseFives);
      localStorage.setItem("LDBDSCOpenTens",  GPOpenTens);
      localStorage.setItem("LDBDSCMidTens",  GPMidTens);
      localStorage.setItem("LDBDSCCloseTens",  GPCloseTens);
      localStorage.setItem("LDBDSCOpenTwenties",  GPOpenTwenties);
      localStorage.setItem("LDBDSCMidTwenties",  GPMidTwenties);
      localStorage.setItem("LDBDSCCloseTwenties",  GPCloseTwenties);
      localStorage.setItem("LDBDSCOpenFithy",  GPOpenFithy);
      localStorage.setItem("LDBDSCMidFithy",  GPMidFithy);
      localStorage.setItem("LDBDSCCloseFithy",  GPCloseFithy);
      localStorage.setItem("LDBDSCOpenHundreds",  GPOpenHundreds);
      localStorage.setItem("LDBDSCMidHundreds",  GPMidHundreds);
      localStorage.setItem("LDBDSCCloseHundreds",  GPCloseHundreds);
      localStorage.setItem("LDBDSCOpenSafeCount",  GPOpenSafeCount);
      localStorage.setItem("LDBDSCMidSafeCount",  GPMidSafeCount);
      localStorage.setItem("LDBDSCCloseSafeCount",  GPCloseSafeCount);
      localStorage.setItem("LDBDSCOpenRegister",  GPOpenRegister);
      localStorage.setItem("LDBDSCMidRegister",  GPMidRegister);
      localStorage.setItem("LDBDSCCloseRegister",  GPCloseRegister);
      localStorage.setItem("LDBDSCOpenTotalSafe",  GPOpenTotalSafe);
      localStorage.setItem("LDBDSCMidTotalSafe",  GPMidTotalSafe);
      localStorage.setItem("LDBDSCCloseTotalSafe",  GPCloseTotalSafe);
      localStorage.setItem("LDBDSCOpenMgrInitials",  GPOpenMgrInitials);
      localStorage.setItem("LDBDSCMidMgrInitials",  GPMidMgrInitials);
      localStorage.setItem("LDBDSCCloseMgrInitials",  GPCloseMgrInitials);
      localStorage.setItem("LDBRDLPosIdealDeposit1",  GPPosIdealDeposit1);
      localStorage.setItem("LDBRDLPosIdealDeposit2",  GPPosIdealDeposit2);
      localStorage.setItem("LDBRDLPosIdealDeposit3",  GPPosIdealDeposit3);
      localStorage.setItem("LDBRDLPosIdealDepositTotal",  GPPosIdealDepositTotal);
      localStorage.setItem("LDBRDLManagerBankDeposit1",  GPManagerBankDeposit1);
      localStorage.setItem("LDBRDLManagerBankDeposit2",  GPManagerBankDeposit2);
      localStorage.setItem("LDBRDLManagerBankDeposit3",  GPManagerBankDeposit3);
      localStorage.setItem("LDBRDLManagerBankDepositTotal",  GPManagerBankDepositTotal);
      localStorage.setItem("LDBRDLVariance1",  GPVariance1);
      localStorage.setItem("LDBRDLVariance2",  GPVariance2);
      localStorage.setItem("LDBRDLVariance3",  GPVariance3);
      localStorage.setItem("LDBRDLVarianceTotal",  GPVarianceTotal);
      localStorage.setItem("LDBRDLMGRsign1",  GPMGRsign1);
      localStorage.setItem("LDBRDLMGRsign2",  GPMGRsign2);
      localStorage.setItem("LDBRDLMGRsign3",  GPMGRsign3);
      localStorage.setItem("LDBRDLMGRsignTotal",  GPMGRsignTotal);
      localStorage.setItem("LDBRDLMGRtookDeposits1",  GPTook1);
      localStorage.setItem("LDBRDLMGRtookDeposits2",  GPTook2);
      localStorage.setItem("LDBRDLMGRtookDeposits3",  GPTook3);
      localStorage.setItem("LDBRDLMGRtookDepositsTotal",  GPTookTotal);
    };

function GPclearStore() {
      localStorage.setItem("LDBDSCOpenPennies",  "");
      localStorage.setItem("LDBDSCMidPennies", "");
      localStorage.setItem("LDBDSCClosePennies", "");
      localStorage.setItem("LDBDSCOpenNickels", "");
      localStorage.setItem("LDBDSCMidNickels", "");
      localStorage.setItem("LDBDSCCloseNickels", "");
      localStorage.setItem("LDBDSCOpenDimes", "");
      localStorage.setItem("LDBDSCMidDimes", "");
      localStorage.setItem("LDBDSCCloseDimes", "");
      localStorage.setItem("LDBDSCOpenQuarters", "");
      localStorage.setItem("LDBDSCMidQuarters", "");
      localStorage.setItem("LDBDSCCloseQuarters", "");
      localStorage.setItem("LDBDSCOpenOnes", "");
      localStorage.setItem("LDBDSCMidOnes", "");
      localStorage.setItem("LDBDSCCloseOnes", "");
      localStorage.setItem("LDBDSCOpenFives", "");
      localStorage.setItem("LDBDSCMidFives", "");
      localStorage.setItem("LDBDSCCloseFives", "");
      localStorage.setItem("LDBDSCOpenTens", "");
      localStorage.setItem("LDBDSCMidTens", "");
      localStorage.setItem("LDBDSCCloseTens", "");
      localStorage.setItem("LDBDSCOpenTens", "");
      localStorage.setItem("LDBDSCMidTens", "");
      localStorage.setItem("LDBDSCCloseTens", "");
      localStorage.setItem("LDBDSCOpenTwenties", "");
      localStorage.setItem("LDBDSCMidTwenties", "");
      localStorage.setItem("LDBDSCCloseTwenties", "");
      localStorage.setItem("LDBDSCOpenFithy", "");
      localStorage.setItem("LDBDSCMidFithy", "");
      localStorage.setItem("LDBDSCCloseFithy", "");
      localStorage.setItem("LDBDSCOpenHundreds", "");
      localStorage.setItem("LDBDSCMidHundreds", "");
      localStorage.setItem("LDBDSCCloseHundreds", "");
      localStorage.setItem("LDBDSCOpenSafeCount", "");
      localStorage.setItem("LDBDSCMidSafeCount", "");
      localStorage.setItem("LDBDSCCloseSafeCount", "");
      localStorage.setItem("LDBDSCOpenRegister", "");
      localStorage.setItem("LDBDSCMidRegister", "");
      localStorage.setItem("LDBDSCCloseRegister", "");
      localStorage.setItem("LDBDSCOpenTotalSafe", "");
      localStorage.setItem("LDBDSCMidTotalSafe", "");
      localStorage.setItem("LDBDSCCloseTotalSafe", "");
      localStorage.setItem("LDBDSCOpenMgrInitials", "");
      localStorage.setItem("LDBDSCMidMgrInitials", "");
      localStorage.setItem("LDBDSCCloseMgrInitials", "");
      localStorage.setItem("LDBRDLPosIdealDeposit1", "");
      localStorage.setItem("LDBRDLPosIdealDeposit2", "");
      localStorage.setItem("LDBRDLPosIdealDeposit3", "");
      localStorage.setItem("LDBRDLPosIdealDepositTotal", "");
      localStorage.setItem("LDBRDLManagerBankDeposit1", "");
      localStorage.setItem("LDBRDLManagerBankDeposit2", "");
      localStorage.setItem("LDBRDLManagerBankDeposit3", "");
      localStorage.setItem("LDBRDLManagerBankDepositTotal", "");
      localStorage.setItem("LDBRDLVariance1", "");
      localStorage.setItem("LDBRDLVariance2", "");
      localStorage.setItem("LDBRDLVariance3", "");
      localStorage.setItem("LDBRDLVarianceTotal", "");
      localStorage.setItem("LDBRDLMGRsign1", "");
      localStorage.setItem("LDBRDLMGRsign2", "");
      localStorage.setItem("LDBRDLMGRsign3", "");
      localStorage.setItem("LDBRDLMGRsignTotal", "");
      localStorage.setItem("LDBRDLMGRtookDeposits1", "");
      localStorage.setItem("LDBRDLMGRtookDeposits2", "");
      localStorage.setItem("LDBRDLMGRtookDeposits3", "");
      localStorage.setItem("LDBRDLMGRtookDepositsTotal", "");
    
      $("#DSCOpenPennies").val(localStorage.getItem("LDBDSCOpenPennies"));
      $("#DSCMidPennies").val(localStorage.getItem("LDBDSCMidPennies"));
      $("#DSCClosePennies").val(localStorage.getItem("LDBDSCClosePennies"));
      $("#DSCOpenNickels").val(localStorage.getItem("LDBDSCOpenNickels"));
      $("#DSCMidNickels").val(localStorage.getItem("LDBDSCMidNickels"));
      $("#DSCCloseNickels").val(localStorage.getItem("LDBDSCCloseNickels"));
      $("#DSCOpenDimes").val(localStorage.getItem("LDBDSCOpenDimes"));
      $("#DSCMidDimes").val(localStorage.getItem("LDBDSCOpenDimes"));
      $("#DSCCloseDimes").val(localStorage.getItem("LDBDSCOpenDimes"));
      $("#DSCOpenQuarters").val(localStorage.getItem("LDBDSCOpenQuarters"));
      $("#DSCMidQuarters").val(localStorage.getItem("LDBDSCMidQuarters"));
      $("#DSCCloseQuarters").val(localStorage.getItem("LDBDSCCloseQuarters"));
      $("#DSCOpenOnes").val(localStorage.getItem("LDBDSCOpenOnes"));
      $("#DSCMidOnes").val(localStorage.getItem("LDBDSCMidOnes"));
      $("#DSCCloseOnes").val(localStorage.getItem("LDBDSCCloseOnes"));
      $("#DSCOpenFives").val(localStorage.getItem("LDBDSCOpenFives"));
      $("#DSCMidFives").val(localStorage.getItem("LDBDSCMidFives"));
      $("#DSCCloseFives").val(localStorage.getItem("LDBDSCCloseFives"));
      $("#DSCOpenTens").val(localStorage.getItem("LDBDSCOpenTens"));
      $("#DSCMidTens").val(localStorage.getItem("LDBDSCMidTens"));
      $("#DSCCloseTens").val(localStorage.getItem("LDBDSCCloseTens"));
      $("#DSCOpenTwenties").val(localStorage.getItem("LDBDSCOpenTwenties"));
      $("#DSCMidTwenties").val(localStorage.getItem("LDBDSCMidTwenties"));
      $("#DSCCloseTwenties").val(localStorage.getItem("LDBDSCCloseTwenties"));
      $("#DSCOpenFifthy").val(localStorage.getItem("LDBDSCOpenFifthy"));
      $("#DSCMidFifthy").val(localStorage.getItem("LDBDSCMidFifthy"));
      $("#DSCCloseFifthy").val(localStorage.getItem("LDBDSCCloseFifthy"));
      $("#DSCOpenHundreds").val(localStorage.getItem("LDBDSCOpenHundreds"));
      $("#DSCMidHundreds").val(localStorage.getItem("LDBDSCMidHundreds"));
      $("#DSCCloseHundreds").val(localStorage.getItem("LDBDSCCloseHundreds"));
      $("#DSCOpenSafeCount").val(localStorage.getItem("LDBDSCOpenSafeCount"));
      $("#DSCMidSafeCount").val(localStorage.getItem("LDBDSCMidSafeCount"));
      $("#DSCCloseSafeCount").val(localStorage.getItem("LDBDSCCloseSafeCount"));
      $("#DSCOpenRegister").val(localStorage.getItem("LDBDSCOpenRegister"));
      $("#DSCMidRegister").val(localStorage.getItem("LDBDSCMidRegister"));
      $("#DSCCloseRegister").val(localStorage.getItem("LDBDSCCloseRegister"));
      $("#DSCOpenTotalSafe").val(localStorage.getItem("LDBDSCOpenTotalSafe"));
      $("#DSCMidTotalSafe").val(localStorage.getItem("LDBDSCMidTotalSafe"));
      $("#DSCCloseTotalSafe").val(localStorage.getItem("LDBDSCCloseTotalSafe"));
      $("#DSCOpenMgrInitials").val(localStorage.getItem("LDBDSCOpenMgrInitials"));
      $("#DSCMidMgrInitials").val(localStorage.getItem("LDBDSCMidMgrInitials"));
      $("#DSCCloseMgrInitials").val(localStorage.getItem("LDBDSCCloseMgrInitials"));
      $("#RDLPosIdealDeposit1").val(localStorage.getItem("LDBRDLPosIdealDeposit1"));
      $("#RDLPosIdealDeposit2").val(localStorage.getItem("LDBRDLPosIdealDeposit2"));
      $("#RDLPosIdealDeposit3").val(localStorage.getItem("LDBLDRDLPosIdealDeposit3"));
      $("#RDLPosIdealDepositTotal").val(localStorage.getItem("LDBRDLPosIdealDepositTotal"));
      $("#RDLManagerBankDeposit1").val(localStorage.getItem("LDBRDLManagerBankDeposit1"));
      $("#RDLManagerBankDeposit2").val(localStorage.getItem("LDBRDLManagerBankDeposit2"));
      $("#RDLManagerBankDeposit3").val(localStorage.getItem("LDBRDLManagerBankDeposit3"));
      $("#RDLManagerBankDepositTotal").val(localStorage.getItem("LDBRDLManagerBankDepositTotal"));
      $("#RDLVariance1").val(localStorage.getItem("LDBRDLVariance1"));
      $("#RDLVariance2").val(localStorage.getItem("LDBRDLVariance2"));
      $("#RDLVariance3").val(localStorage.getItem("LDBRDLVariance3"));
      $("#RDLVarianceTotal").val(localStorage.getItem("LDBRDLVarianceTotal"));
      $("#RDLMGRsign1").val(localStorage.getItem("LDBRDLMGRsign1"));
      $("#RDLMGRsign2").val(localStorage.getItem("LDBRDLMGRsign2"));
      $("#RDLMGRsign3").val(localStorage.getItem("LDBRDLMGRsign3"));
      $("#RDLMGRsignTotal").val(localStorage.getItem("LDBRDLMGRsignTotal"));
      $("#RDLMGRtookDeposits1").val(localStorage.getItem("LDBRDLMGRtookDeposits1"));
      $("#RDLMGRtookDeposits2").val(localStorage.getItem("LDBRDLMGRtookDeposits2"));
      $("#RDLMGRtookDeposits3").val(localStorage.getItem("LDBRDLMGRtookDeposits3"));
      $("#RDLMGRtookDepositsTotal").val(localStorage.getItem("LDBRDLMGRtookDepositsTotal"));

    };


